options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/student-project-backend/github.com/jonaspedersendev/himmerland-booking-system:$COMMIT_SHA'
      - './backend'

   # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/student-project-backend/github.com/jonaspedersendev/himmerland-booking-system:$COMMIT_SHA'

  # Step 3: Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'himmerland-booking-system'
      - '--image'
      - 'gcr.io/student-project-backend/github.com/jonaspedersendev/himmerland-booking-system:$COMMIT_SHA'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/student-project-backend/github.com/jonaspedersendev/himmerland-booking-system:$COMMIT_SHA'
