options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/student-project-backend/github.com/jonaspedersendev/himmerland-booking-system:$COMMIT_SHA'
      - './backend'
images:
  - 'gcr.io/student-project-backend/github.com/jonaspedersendev/himmerland-booking-system:$COMMIT_SHA'
